### PR TITLE
Switch to 11ty

### PR DESCRIPTION
**Pull request by BigBlueHat**
This is currently setup targeting Cloudflare Pages as the deployment mechanism. However, this could also be deployed via GitHub Pages with the use of a GitHub Action--which I can wire-up if we pick that over the Cloudflare-based approach.

Key feature offered by Cloudflare Pages is previews of any PR/branch/commit:
https://bbh-chapi-io.pages.dev/

It makes reviewing content changes far more pleasant. 😃

### CODE REVIEW

**Comment by mattcollier** [comment]
@BigBlueHat can you say more about the github only solution which you say is possible?

**Comment by BigBlueHat** [comment]
> @BigBlueHat can you say more about the github only solution which you say is possible?

The GitHub Action would watch commits to `main`, build the site, and commit the generated static files to the `gh-pages` branch which would become the new production branch (something we'd change in the current settings).

The Cloudflare Pages approach doesn't require any "robo commits" and keeps the built assets out of the commit log of any branch--which is greatly preferred. It would also come with preview branches per PR/commit--which would not likely be possible with the GitHub Action approach.

**Comment by BigBlueHat** [comment]
@mattcollier actually... The commits may be avoidable. Still digging through the options. I'll report back once I've got something running on my fork.

**Review by dlongley — APPROVED** [review]
RSLGTM

**Review by mattcollier — APPROVED** [review]

**Pull request merged**
